config.vapi: config.h
	rm -f $@
	{ \
	echo 'namespace Config {'; \
	sed -e '/#define.*"$$/s/#define \([A-Z_]*\) .*/[CCode (cname = "\1")]\npublic static const string \1;/;/#define.*[0-9]$$/s/#define \([A-Z_]*\) .*/[CCode (cname = "\1")]\npublic static const int \1;/;/#define.*$$/d;' $< ; \
	echo '}' ; \
	} > $@

BUILT_SOURCES += config.vapi
DISTCLEANFILES += config.vapi
