#! /bin/sh
RPMDEVROOT=~/rpmbuild
uname=`uname -i`
if [ ! -d $RPMDEVROOT ]; then
	echo edit this file to update RPMDEVROOT
	exit 1;
fi;

echo svn version is `svnversion`, press enter to edit .spec
echo type the svn number you want for this build
read version
if [ x$version == x ]; then 
	echo input version
	exit 1;
fi;

echo type the dist number you want for this build '('empty for 1')'
read dist
[ x$dist == x ] && dist=1

cat gnome-globalmenu.spec.tmpl | \
sed 's/@SVNVERSION@/'$version'/' | \
sed 's/@RELEASE@/'$dist'/' >  gnome-globalmenu.spec
make dist
cp gnome-globalmenu-0.6.tar.gz $RPMDEVROOT/SOURCES/
rpmbuild -ba *.spec && \
rm gnome-globalmenu.spec
cp gnome-globalmenu-0.6.tar.gz gnome-globalmenu-0.6.svn$version.tar.gz
