namespace Gnomenu {
	class WindowActionMenu {
		public static const string ICON_CLOSE = """pixbuf:R2RrUAAAAL0CAQACAAAAQAAAABAAAAAQswAAAACCAAAA/4YAAAAAggAAAP+GAAAAAIMAAAD/hAAAAACDAAAA/4cAAAAAgwAAAP+CAAAAAIMAAAD/iQAAAACGAAAA/4sAAAAAhAAAAP+MAAAAAIQAAAD/iwAAAACGAAAA/4kAAAAAgwAAAP+CAAAAAIMAAAD/hwAAAACDAAAA/4QAAAAAgwAAAP+GAAAAAIIAAAD/hgAAAACCAAAA/7MAAAAA""";
		public static const string ICON_MAXIMIZE = """pixbuf:R2RrUAAAAL0CAQACAAAAQAAAABAAAAAQswAAAACKAAAA/4YAAAAAigAAAP+GAAAAAIoAAAD/hgAAAAABAAAA/4ji4t4AAQAAAP+GAAAAAAEAAAD/iOLi3gABAAAA/4YAAAAAAQAAAP+I4uLeAAEAAAD/hgAAAAABAAAA/4ji4t4AAQAAAP+GAAAAAAEAAAD/iOLi3gABAAAA/4YAAAAAAQAAAP+I4uLeAAEAAAD/hgAAAACKAAAA/7MAAAAA""";
		public static const string ICON_MINIMIZE = """pixbuf:R2RrUAAAAEACAQACAAAAQAAAABAAAAAQ/wAAAACkAAAAAIoAAAD/hgAAAACKAAAA/4YAAAAAigAAAP+zAAAAAA==""";
	}
}
