#ifndef _IPC_H_
#define _IPC_H_
#define IPC_SERVER_TITLE "GNOMENU_IPC_SERVER"
#define IPC_CLIENT_TITLE "GNOMENU_IPC_CLIENT"
#define IPC_CLIENT_MESSAGE_CALL (gdk_atom_intern("GNOMENU_IPC_CALL", FALSE))
#define IPC_CLIENT_MESSAGE_NEGO (gdk_atom_intern("GNOMENU_IPC_NEGO", FALSE))
#define IPC_CLIENT_MESSAGE_EVENT (gdk_atom_intern("GNOMENU_IPC_EVENT", FALSE))
#define IPC_PROPERTY_CID (gdk_atom_intern("GNOMENU_IPC_CID", FALSE))
#define IPC_PROPERTY_CALL (gdk_atom_intern("GNOMENU_IPC_CALL", FALSE))
#define IPC_PROPERTY_RETURN (gdk_atom_intern("GNOMENU_IPC_RETURN", FALSE))
#define IPC_PROPERTY_EVENT (gdk_atom_intern("GNOMENU_IPC_EVENT", FALSE))
#define IPC_PROPERTY_SERVERCALL (gdk_atom_intern("GNOMENU_IPC_SERVERCALL", FALSE))
#define IPC_PROPERTY_SERVERRETURN (gdk_atom_intern("GNOMENU_IPC_SERVERRETURN", FALSE))

#endif
